### ISSUE TITLE
cp:404 failing due to no build/404.html file.

### ISSUE THREAD

**Issue by softgripper** [svelte-add/firebase-hosting#2]
When building 
```
pnpm build
```
the following occurs

```
> xxx@0.0.1 cp:404 /home/xxx/Development/xxx
> ncp build/404/index.html build/404.html

There were errors during the copy.
Error: ENOENT: no such file or directory, lstat '/home/xxx/Development/xxx/build/404/index.html'
 ERROR  Command failed with exit code 1.
ERROR: "cp:404" exited with 1.
 ERROR  Command failed with exit code 1.
```

There is no build folder.

**Comment by babichjacob** [comment]
Thanks for the report! It now works with the extra `adapt` step that the newest version(s) of the adapters need. The docs have been updated to reflect this: https://github.com/svelte-add/firebase-hosting/commit/7173eabaff173613906fedeae96fac00612efdb6
