### ISSUE TITLE
build-and-deploy.yml has quote error preventing deploy

### ISSUE THREAD

**Issue by softgripper** [svelte-add/firebase-hosting#3]
Deploy line needs to be changed to surround the git message with quotes

```json
run: "pnpm run deploy -- -m \"${{ github.event.head_commit.message }}\""
```

Without this - github yields the following
```
Run pnpm run deploy -- -m build: deployed from github
  pnpm run deploy -- -m build: deployed from github
  shell: /bin/bash -e {0}
  env:
    FIREBASE_TOKEN: ***

> digitalgrip@0.0.1 deploy /home/runner/work/digitalgrip/digitalgrip
> firebase deploy "-m" "build:" "deployed" "from" "github"
ERROR  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by babichjacob** [comment]
Did that fix it?

**Comment by softgripper** [comment]
If you're able to auto publish to firebase with a multi word commit message - then yes.  Previously it should never have worked unless perhaps a single word commit message.

I'm hesitant to apply the template over my existing project as the balancing act of getting things working seems to be just right!

**Comment by babichjacob** [comment]
Worked for simple multi-word messages like this:
```
⚡️ feat: update index (homepage)
```

But broke for this:
```
🐛 fix: "test" 'how ''''' is this "" for a test"
```

Trying to find how to shell escape in GitHub Actions.

Update: Fix coming soon.
